CREATE TRIGGER Tr_RecordedContracts
ON Insurance FOR INSERT
AS BEGIN
INSERT INTO NewContract VALUES (GETDATE(), SYSTEM_USER)
END
GO

INSERT INTO Insurance VALUES (600614,'MetLife','2035/04/29',45,160,160);

SELECT * FROM NewContract;